// Shared MCP core: tool/resource definitions + JSON-RPC dispatch, used by BOTH transports —
// the stdio server (mcp-graph.js) and the daemon's HTTP /mcp endpoint (for custom connectors).
// Tools operate by calling the daemon's existing HTTP API via an injected `call(method,path,body)`.
'use strict';
const http = require('http');
const fs = require('fs');
const os = require('os');
const path = require('path');

const TOKEN_BASE = process.env.CLAUDE_PLUGIN_DATA || path.join(os.homedir(), '.claude', 'orchestrator');
// Auth token: env ORCH_TOKEN, else BASE/token file, else null (auth off — back-compat).
function readToken() {
  if (process.env.ORCH_TOKEN) return process.env.ORCH_TOKEN.trim() || null;
  try { return fs.readFileSync(path.join(TOKEN_BASE, 'token'), 'utf8').trim() || null; } catch { return null; }
}

const UI_URI = 'ui://orchestrator/graph';
const UI_MIME = 'text/html;profile=mcp-app';
const PORT = process.env.ORCH_PORT ? Number(process.env.ORCH_PORT) : 8787;
const DEFAULT_PROTOCOL = '2025-06-18';

const q = (o) => Object.entries(o).filter(([, v]) => v != null).map(([k, v]) => `${k}=${encodeURIComponent(v)}`).join('&');

function uiHtml() {
  try { return fs.readFileSync(path.join(__dirname, '..', 'public', 'inline.html'), 'utf8'); }
  catch { return '<!doctype html><body>inline.html missing</body>'; }
}

// An HTTP client bound to the daemon port — same for stdio (mcp-graph) and the daemon's self-calls.
function makeCall(port) {
  return (method, p, body) => new Promise((resolve) => {
    const data = body ? JSON.stringify(body) : null;
    const headers = {};
    if (data) { headers['content-type'] = 'application/json'; headers['content-length'] = Buffer.byteLength(data); }
    const tok = readToken(); if (tok) headers['authorization'] = `Bearer ${tok}`;
    const req = http.request({ host: '127.0.0.1', port, path: p, method, headers },
      (res) => {
        const chunks = [];
        res.on('data', (c) => chunks.push(c));
        res.on('end', () => {
          const b = Buffer.concat(chunks).toString('utf8');
          let parsed; try { parsed = b ? JSON.parse(b) : {}; } catch { parsed = { raw: b }; }
          if (res.statusCode >= 400 && !(parsed && parsed.error)) parsed = { error: `daemon HTTP ${res.statusCode}`, status: res.statusCode, body: parsed };
          resolve(parsed);
        });
      });
    req.on('error', (e) => resolve({ error: `daemon unreachable on :${port} (${e.code}). Is the orchestrator daemon running?` }));
    if (data) req.write(data); req.end();
  });
}

const TOOLS = [
  { name: 'get_full_graph', description: 'Get the current workspace task graph: all tasks (with derived status not_ready/ready/in_progress/tested/done/failed/canceled and dependencies), cross-workspace ghost stubs, overlay edges, and a summary.', inputSchema: { type: 'object', properties: {}, additionalProperties: false }, run: (a, call) => call('GET', '/state') },
  { name: 'get_adjacent', description: 'Get one task plus its immediate neighbourhood: dependencies, cross-workspace ghost dependencies, and dependents.', inputSchema: { type: 'object', properties: { task_key: { type: 'string' } }, required: ['task_key'], additionalProperties: false }, run: (a, call) => call('GET', `/task/adjacent?${q({ key: a.task_key })}`) },
  { name: 'get_dependency_tree', description: 'Walk VERTICALLY up a task\'s dependency chain (transitive deps) returning each ancestor with summary + depth. Ghost deps come back as a frontier (use peek_workspace).', inputSchema: { type: 'object', properties: { task_key: { type: 'string' }, depth: { type: 'number' } }, required: ['task_key'], additionalProperties: false }, run: (a, call) => call('GET', `/task/tree?${q({ key: a.task_key, depth: a.depth })}`) },
  { name: 'start_task', description: 'Claim a task and mark it in_progress, recording which agent is working it (drives the live graph). Call FIRST when you begin a task. Safe-claim (CAS): refuses (409) to claim a task that is "canceled" (terminal) or already in_progress by a DIFFERENT agent — an agent never resurrects a canceled task or steals a live claim. Pass force:true only for a deliberate takeover.', inputSchema: { type: 'object', properties: { task_key: { type: 'string' }, agent_id: { type: 'string' }, force: { type: 'boolean' } }, required: ['task_key'], additionalProperties: false }, run: (a, call) => call('POST', '/overlay/status', { key: a.task_key, status: 'in_progress', agent_id: a.agent_id, force: a.force }) },
  { name: 'complete_task', description: 'Mark a task done and record a CONCISE summary (the interface other tasks pull as cheap base context). Keep it short.', inputSchema: { type: 'object', properties: { task_key: { type: 'string' }, summary: { type: 'string' }, agent_id: { type: 'string' } }, required: ['task_key', 'summary'], additionalProperties: false }, run: (a, call) => call('POST', '/overlay/status', { key: a.task_key, status: 'done', summary: a.summary, agent_id: a.agent_id }) },
  { name: 'set_status', description: 'Set the overlay status for a task. Allowed: in_progress, tested, done, failed, canceled (also not_ready/ready, normally derived). Prefer start_task/complete_task. Concurrency: pass expected_status to compare-and-set (409 if the status changed under you). "canceled" is terminal — leaving it (e.g. back to in_progress) needs force:true. Setting "canceled" also raises a cooperative cancel flag (see get_task_detail.cancel_requested).', inputSchema: { type: 'object', properties: { task_key: { type: 'string' }, status: { type: 'string', enum: ['not_ready', 'ready', 'in_progress', 'tested', 'done', 'failed', 'canceled'] }, note: { type: 'string' }, expected_status: { type: 'string' }, force: { type: 'boolean' } }, required: ['task_key', 'status'], additionalProperties: false }, run: (a, call) => call('POST', '/overlay/status', { key: a.task_key, status: a.status, note: a.note, expected_status: a.expected_status, force: a.force }) },
  { name: 'get_dependency_summaries', description: 'TIER 1 (cheap, do first): concise summaries of a task\'s dependencies — enough to start without loading full context.', inputSchema: { type: 'object', properties: { task_key: { type: 'string' } }, required: ['task_key'], additionalProperties: false }, run: (a, call) => call('GET', `/task/context?${q({ key: a.task_key })}`) },
  { name: 'get_task_detail', description: 'TIER 2 (on demand): full detail for one task — knowledge items, summary, assigned agent, token usage, transcript pointer.', inputSchema: { type: 'object', properties: { task_key: { type: 'string' } }, required: ['task_key'], additionalProperties: false }, run: (a, call) => call('GET', `/task/detail?${q({ key: a.task_key })}`) },
  { name: 'attach_knowledge', description: 'Attach a Tier-2 knowledge item to a task. item = { type: "file"|"snippet"|"link"|"note", value, ... }.', inputSchema: { type: 'object', properties: { task_key: { type: 'string' }, item: { type: 'object' } }, required: ['task_key', 'item'], additionalProperties: false }, run: (a, call) => call('POST', '/overlay/knowledge', { key: a.task_key, item: a.item }) },
  { name: 'record_decision', description: "Capture a durable decision, rationale, or finding from the conversation as a NOTE node in the graph (NOT a todo). It becomes Tier-1 context for related future tasks via context edges + suggest_links. Use when a turn produces lasting knowledge, or when the user says 'remember this'.", inputSchema: { type: 'object', properties: { title: { type: 'string' }, summary: { type: 'string' }, knowledge: { type: 'array' } }, required: ['title', 'summary'], additionalProperties: false }, run: (a, call) => call('POST', '/overlay/note', { title: a.title, summary: a.summary, knowledge: a.knowledge, created_by: 'main' }) },
  { name: 'add_dependency', description: 'Add a dependency edge. kind:"blocking" (default) = `to` is blocked by `from` (true prerequisite). kind:"context" = non-blocking link so `from`\'s summary flows into `to` as Tier-1 context EVEN IF `from` is already done (use to wire a new task to relevant existing/completed work). weight (0..1, context edges only) = optional relevance scalar for relevance-ordered traversal; omit ⇒ default. For a CROSS-WORKSPACE ghost edge set from_workspace to the provider\'s absolute path.', inputSchema: { type: 'object', properties: { from: { type: 'string' }, to: { type: 'string' }, from_workspace: { type: 'string' }, kind: { type: 'string', enum: ['blocking', 'context'] }, weight: { type: 'number' } }, required: ['from', 'to'], additionalProperties: false }, run: (a, call) => call('POST', '/overlay/edge', { from: a.from, to: a.to, fromWorkspace: a.from_workspace, kind: a.kind, weight: a.weight }) },
  { name: 'remove_dependency', description: 'Remove a dependency edge from -> to (idempotent). Pass kind:"blocking"|"context" to remove only that kind; omit to remove every edge between them. For a CROSS-WORKSPACE ghost edge set from_workspace to the provider\'s absolute path. Use to re-parallelize a graph by dropping a stale prerequisite.', inputSchema: { type: 'object', properties: { from: { type: 'string' }, to: { type: 'string' }, from_workspace: { type: 'string' }, kind: { type: 'string', enum: ['blocking', 'context'] } }, required: ['from', 'to'], additionalProperties: false }, run: (a, call) => call('POST', '/overlay/edge/remove', { from: a.from, to: a.to, fromWorkspace: a.from_workspace, kind: a.kind }) },
  { name: 'list_agents', description: 'List every known agent across sessions with its task, session, workspace, startedAt and current cooperative-stop flag. Use to SEE whether another session has a worker running on this graph before you act.', inputSchema: { type: 'object', properties: {}, additionalProperties: false }, run: (a, call) => call('GET', '/agents') },
  { name: 'request_agent_stop', description: 'Cooperatively stop a worker by agent_id, or by task_key (resolved via its assignee). Sets an advisory stop flag — there is NO cross-process kill; the worker is expected to poll list_agents (or /agent/stop-requested) and self-terminate. Use to stand down a colliding worker in another session.', inputSchema: { type: 'object', properties: { agent_id: { type: 'string' }, task_key: { type: 'string' } }, additionalProperties: false }, run: (a, call) => call('POST', '/agent/stop', { agent_id: a.agent_id, task_key: a.task_key }) },
  { name: 'suggest_links', description: 'Suggest existing tasks (INCLUDING completed ones) that a task should link to, ranked by label+summary overlap. Call right after creating a task: link DONE matches as kind:"context" so their summaries become context, and true prerequisites as kind:"blocking" — this stops new tasks from piling up as disconnected root nodes.', inputSchema: { type: 'object', properties: { task_key: { type: 'string' } }, required: ['task_key'], additionalProperties: false }, run: (a, call) => call('GET', `/task/suggest?${q({ key: a.task_key })}`) },
  { name: 'get_learnings', description: "Aggregate the graph's accumulated learning (attempt verdicts, recent failures, recent completions) — the digest a planner reads to decide what to try next. Pass compact:true for a lean payload (trimmed verdicts + rejected ledger only, recent/failures dropped) to cut re-attended context cost.", inputSchema: { type: 'object', properties: { compact: { type: 'boolean' } }, additionalProperties: false }, run: (a, call) => call('GET', a.compact ? '/learnings?compact=1' : '/learnings') },
  { name: 'search_knowledge', description: 'Retrieve the most relevant knowledge notes (decisions / gotchas / constraints) for a free-text query — query-by-text, no anchor task needed. Use before solving a task to recall prior resolutions.', inputSchema: { type: 'object', properties: { query: { type: 'string' }, k: { type: 'number' } }, required: ['query'], additionalProperties: false }, run: (a, call) => call('GET', `/search?${q({ q: a.query, k: a.k })}`) },
  { name: 'next_action', description: 'HEARTBEAT (drives the WHOLE loop registry in ONE call): returns { loops: [ { loopId, action: spawn|idle|plan|stop|await_user, tasks?, next_poll_seconds?, budget_remaining } ] } — one entry per ACTIVE loop. Fan out spawns per loopId; reschedule ONE wakeup at the MIN next_poll_seconds across active loops; the whole heartbeat is done only when every entry reports stop. action:plan means that loop drained but self-planning is on.', inputSchema: { type: 'object', properties: {}, additionalProperties: false }, run: (a, call) => call('GET', '/next-action') },
  { name: 'loop_start', description: 'Start a heartbeat loop and INSERT it into the registry (never clobbers an existing loop). Pass explicit token controls (tokenBudget, maxIterations, minPoll, maxPoll, estPerTick, batch) and an optional `session` (the driving conversation, so a cooperative-stop on its claimed task halts THIS loop within one tick). Optional `loopId` to restart a specific loop in place; otherwise the daemon mints a UUID. Returns { ok, loopId, loop }. Hard caps.', inputSchema: { type: 'object', properties: { loopId: { type: 'string' }, tokenBudget: { type: 'number' }, maxIterations: { type: 'number' }, minPoll: { type: 'number' }, maxPoll: { type: 'number' }, estPerTick: { type: 'number' }, batch: { type: 'number' }, session: { type: 'string' } }, additionalProperties: false }, run: (a, call) => call('POST', '/loop/start', a) },
  { name: 'loop_stop', description: 'Stop a specific heartbeat loop by loopId (required). Returns { ok, loopId }.', inputSchema: { type: 'object', properties: { loopId: { type: 'string' } }, required: ['loopId'], additionalProperties: false }, run: (a, call) => call('POST', '/loop/stop', a) },
  { name: 'loop_status', description: 'Get loop state. With loopId: that loop\'s entry { active, iterations, spent, budget, config, ... }. Without: { loops: { [loopId]: entry } } for the whole registry.', inputSchema: { type: 'object', properties: { loopId: { type: 'string' } }, additionalProperties: false }, run: (a, call) => call('GET', a && a.loopId ? `/loop/status?loopId=${encodeURIComponent(a.loopId)}` : '/loop/status') },
  { name: 'peek_workspace', description: 'Load another workspace\'s full task graph on demand (does not change current). Inspect a ghost dependency\'s source.', inputSchema: { type: 'object', properties: { workspace: { type: 'string' } }, required: ['workspace'], additionalProperties: false }, run: (a, call) => call('GET', `/peek?${q({ workspace: a.workspace })}`) },
  { name: 'set_task_repo', description: 'Set (or clear, with an empty repo_path) the TARGET git repo path a task\'s git ops (branch_task / merge_attempt / remove_worktree / git_status) run against, when it differs from the daemon workspace. Persisted on the task node; thereafter those tools resolve this repo automatically. Resolution order is explicit repo_path arg > this task field > workspace.', inputSchema: { type: 'object', properties: { task_key: { type: 'string' }, repo_path: { type: 'string' } }, required: ['task_key'], additionalProperties: false }, run: (a, call) => call('POST', '/git/repo', { key: a.task_key, repo_path: a.repo_path }) },
  { name: 'set_task_metric', description: 'Set (or clear, with an empty spec) the INLINE metric spec a task/problem node is optimizing, for the metric-driven loop. spec = { metric (objective name/label), direction ("min"|"max"), measure_command (shell command run later in the attempt worktree that emits the metric), parse? (how to extract a number — e.g. a regex or "last_number"), target? (threshold), guardrails? (array of { metric, direction, measure_command, parse? } that must-not-regress) }. Validated server-side: metric/direction/measure_command required, direction ∈ {min,max}. Persisted on the task node; surfaces as `metric` on the node + /task/detail so the measure node and judge can read it.', inputSchema: { type: 'object', properties: { task_key: { type: 'string' }, spec: { type: 'object' } }, required: ['task_key'], additionalProperties: false }, run: (a, call) => call('POST', '/task/metric', { key: a.task_key, spec: a.spec }) },
  { name: 'measure_task', description: 'Run the task\'s inline metric spec and store the measured value(s) on the node — the MEASURE half of the metric-driven loop. Runs measure_command (+ each guardrail) in the attempt\'s git worktree (branch_task) and parses a number via the spec\'s `parse`. Pass baseline:true to instead measure the repo\'s current main (repo root, no attempt) and store it as the judge\'s reference. Targets the task\'s repo (set_task_repo) or repo_path, else the workspace. Requires a metric spec (set_task_metric) and a git repo (git_init). Result surfaces as `measurement` on the node + /task/detail.', inputSchema: { type: 'object', properties: { task_key: { type: 'string' }, baseline: { type: 'boolean' }, repo_path: { type: 'string' } }, required: ['task_key'], additionalProperties: false }, run: (a, call) => call('POST', '/task/measure', { key: a.task_key, baseline: a.baseline, repo_path: a.repo_path }) },
  { name: 'set_task_benchmark', description: 'Set (or clear, with an empty benchmark) the researched competitor/industry-average BENCHMARK for a task\'s metric — the EXTERNAL reference the judge compares the winning attempt\'s measured value against, beyond our own baseline. benchmark = { metric (must name the same objective as the metric spec), value (number), unit? (e.g. "ms"), source (string/url for provenance), note?, confidence? ("low"|"med"|"high"), researched_at? }. Validated server-side: metric/value/source required, confidence ∈ {low,med,high}. Persisted on the task node; surfaces as `benchmark` on the node + /task/detail. Absent ⇒ baseline-only judging (back-compat). Set by the self-learn-benchmark research agent.', inputSchema: { type: 'object', properties: { task_key: { type: 'string' }, benchmark: { type: 'object' } }, required: ['task_key'], additionalProperties: false }, run: (a, call) => call('POST', '/task/benchmark', { key: a.task_key, benchmark: a.benchmark }) },
  { name: 'git_init', description: 'Initialize git in the target repo so attempts can branch (idempotent). Run once before branch_task. Targets repo_path if given, else the workspace.', inputSchema: { type: 'object', properties: { repo_path: { type: 'string' }, task_key: { type: 'string' } }, additionalProperties: false }, run: (a, call) => call('POST', '/git/init', { key: a.task_key, repo_path: a.repo_path }) },
  { name: 'branch_task', description: 'Create an isolated git worktree + branch (orch/attempt/<key>) for a task attempt, recorded on the task node. The foundation of side-by-side experiment isolation. Targets the task\'s repo (set_task_repo) or repo_path, else the workspace.', inputSchema: { type: 'object', properties: { task_key: { type: 'string' }, repo_path: { type: 'string' } }, required: ['task_key'], additionalProperties: false }, run: (a, call) => call('POST', '/git/worktree', { key: a.task_key, repo_path: a.repo_path }) },
  { name: 'remove_worktree', description: 'Remove a task attempt\'s git worktree and delete its branch (idempotent cleanup). Targets the task\'s repo (set_task_repo) or repo_path, else the workspace.', inputSchema: { type: 'object', properties: { task_key: { type: 'string' }, repo_path: { type: 'string' } }, required: ['task_key'], additionalProperties: false }, run: (a, call) => call('POST', '/git/worktree/remove', { key: a.task_key, repo_path: a.repo_path }) },
  { name: 'git_status', description: 'Report whether the target repo is a git repo and list active attempt worktrees. Targets the task\'s repo (set_task_repo via task_key) or repo_path, else the workspace.', inputSchema: { type: 'object', properties: { task_key: { type: 'string' }, repo_path: { type: 'string' } }, additionalProperties: false }, run: (a, call) => call('GET', `/git/status?${q({ key: a.task_key, repo_path: a.repo_path })}`) },
  { name: 'merge_attempt', description: 'Merge a winning attempt\'s branch (orch/attempt/<key>) back into the base. Returns {merged} or {conflict, files}. The merge half of the judge/merge-back loop. Targets the task\'s repo (set_task_repo) or repo_path, else the workspace.', inputSchema: { type: 'object', properties: { task_key: { type: 'string' }, repo_path: { type: 'string' } }, required: ['task_key'], additionalProperties: false }, run: (a, call) => call('POST', '/git/merge', { key: a.task_key, repo_path: a.repo_path }) },
  { name: 'request_guidance', description: 'Halt the autonomous loop and ask the user. Call instead of guessing when you hit a decision the user must make (ambiguous intent, irreversible/outward action, low-confidence high-impact, repeated failure, scope expansion).', inputSchema: { type: 'object', properties: { question: { type: 'string' }, context: { type: 'string' }, trigger: { type: 'string' } }, required: ['question'], additionalProperties: false }, run: (a, call) => call('POST', '/guidance', { question: a.question, context: a.context, trigger: a.trigger }) },
  { name: 'list_guidance', description: 'List unresolved guidance questions the loop is currently waiting on the user to answer.', inputSchema: { type: 'object', properties: {}, additionalProperties: false }, run: (a, call) => call('GET', '/guidance') },
  { name: 'supersede_task', description: 'Retire an old task in favor of a replacement, linking them, so a replan reconciles cleanly instead of leaving orphaned duplicates.', inputSchema: { type: 'object', properties: { old_task_key: { type: 'string' }, new_task_key: { type: 'string' }, reason: { type: 'string' } }, required: ['old_task_key', 'new_task_key'], additionalProperties: false }, run: (a, call) => call('POST', '/supersede', { old_key: a.old_task_key, new_key: a.new_task_key, reason: a.reason }) },
  { name: 'show_dashboard', description: 'Render the orchestrator task-graph dashboard INLINE in the conversation (interactive, live-updating). Use when the user wants to SEE the graph without a browser.', inputSchema: { type: 'object', properties: {}, additionalProperties: false }, meta: { ui: { resourceUri: UI_URI, visibility: ['model', 'app'], csp: { connectDomains: [`http://localhost:${PORT}`, `http://127.0.0.1:${PORT}`, 'https://localhost:8788', 'https://127.0.0.1:8788'] } } }, run: () => Promise.resolve({ rendered: true, note: 'Dashboard shown inline; it polls the daemon live.' }) },
];
const TOOL_BY_NAME = Object.fromEntries(TOOLS.map((t) => [t.name, t]));

// Handle one JSON-RPC message. Returns the response object, or undefined for notifications.
async function handleRpc(msg, ctx) {
  const { id, method, params } = msg;
  const call = ctx.call, html = ctx.uiHtml || uiHtml;
  if (method === 'initialize') return { jsonrpc: '2.0', id, result: { protocolVersion: (params && params.protocolVersion) || DEFAULT_PROTOCOL, capabilities: { tools: {}, resources: {}, extensions: { 'io.modelcontextprotocol/ui': { mimeTypes: [UI_MIME] } } }, serverInfo: { name: 'orchestrator-graph', version: '0.1.0' } } };
  if (method === 'notifications/initialized' || method === 'initialized') return undefined;
  if (method === 'ping') return { jsonrpc: '2.0', id, result: {} };
  if (method === 'tools/list') return { jsonrpc: '2.0', id, result: { tools: TOOLS.map((t) => ({ name: t.name, description: t.description, inputSchema: t.inputSchema, ...(t.meta ? { _meta: t.meta } : {}) })) } };
  if (method === 'resources/list') return { jsonrpc: '2.0', id, result: { resources: [{ uri: UI_URI, name: 'Orchestrator dashboard', mimeType: UI_MIME, description: 'Live task dependency graph (inline)' }] } };
  if (method === 'resources/read') {
    if (params && params.uri === UI_URI) return { jsonrpc: '2.0', id, result: { contents: [{ uri: UI_URI, mimeType: UI_MIME, text: html() }] } };
    return { jsonrpc: '2.0', id, error: { code: -32602, message: `unknown resource: ${params && params.uri}` } };
  }
  if (method === 'tools/call') {
    const tool = TOOL_BY_NAME[params && params.name];
    if (!tool) return { jsonrpc: '2.0', id, error: { code: -32602, message: `unknown tool: ${params && params.name}` } };
    try { const out = await tool.run(params.arguments || {}, call); return { jsonrpc: '2.0', id, result: { content: [{ type: 'text', text: JSON.stringify(out, null, 2) }], isError: !!(out && out.error) } }; }
    catch (e) { return { jsonrpc: '2.0', id, result: { content: [{ type: 'text', text: `error: ${e.message}` }], isError: true } }; }
  }
  if (id != null) return { jsonrpc: '2.0', id, error: { code: -32601, message: `method not found: ${method}` } };
  return undefined;
}

module.exports = { UI_URI, UI_MIME, DEFAULT_PROTOCOL, TOOLS, handleRpc, makeCall, uiHtml, readToken };
