# Generates .fb-infer-config.toml from .env.local.
# Run whenever your CLAUDE_CODE_OAUTH_TOKEN changes.
# Output is gitignored (.fb-infer-config*.toml).

$envFile = Join-Path $PSScriptRoot ".." ".env.local"
$outFile = Join-Path $PSScriptRoot ".." ".fb-infer-config.toml"

if (-not (Test-Path $envFile)) {
    Write-Error ".env.local not found at $envFile"
    exit 1
}

$token = Get-Content $envFile | Where-Object { $_ -match "^CLAUDE_CODE_OAUTH_TOKEN=" } | ForEach-Object { ($_ -split "=", 2)[1] }

if (-not $token) {
    Write-Error "CLAUDE_CODE_OAUTH_TOKEN not found in .env.local"
    exit 1
}

@"
# Local inference config — gitignored, never commit.
# Generated by scripts/gen-fb-infer-config.ps1 from .env.local.

[env]
HF_TOKEN = ""

# Agent env vars forwarded into Docker container
[infer_config.claude_code]
CLAUDE_CODE_OAUTH_TOKEN = "$token"
FB_KB_PATH = ""
"@ | Out-File -FilePath $outFile -Encoding utf8

Write-Host "Wrote $outFile (token length $($token.Length))"
