'use strict';

function gitTools(deps) {
  const { q, UI_URI, PORT, runSubconsciousAssignment } = deps;
  return [
  { name: 'configure_task', description: 'Backcompat/internal escape hatch for configuring execution settings directly; routine task prep should use subconscious_assignment action:"prepare". Pass task_key plus ANY of the optional fields; each provided field is applied in order (repo_path → test_cmd → metric → benchmark) with per-field results. Omitted fields are untouched. FIELDS: `repo_path` (string; clear with "") = REPO TARGETING — the TARGET git repo path the task\'s git ops (branch_task / merge_attempt / remove_worktree / measure_task) run against when it differs from the daemon workspace; persisted on the task node, resolution order: explicit repo_path arg > this task field > workspace. `test_cmd` (string; clear with ""; requires `repo_path` in the same call since test commands are keyed by ABSOLUTE repo path) = STORED TEST COMMAND — how that repo\'s test suite is run (e.g. "npm test"); STORE/RETRIEVE ONLY: the daemon never executes it, agents (e.g. the nightly QA loop) read it back (as `test_cmd` on get_task_detail for tasks whose repo matches) and run it themselves. `metric` (object; clear with {}) = INLINE METRIC SPEC the task/problem node is optimizing, for the metric-driven loop: { metric (objective name/label), direction ("min"|"max"), measure_command (shell command run later in the attempt worktree that emits the metric), parse? (e.g. a regex or "last_number"), target? (threshold), guardrails? (array of { metric, direction, measure_command, parse? } that must-not-regress) }; validated server-side (metric/direction/measure_command required, direction ∈ {min,max}); surfaces as `metric` on the node + /task/detail so the measure node and judge can read it. `benchmark` (object; clear with {}) = EXTERNAL BENCHMARK — the researched competitor/industry-average reference the judge compares the winning attempt\'s measured value against, beyond our own baseline: { metric (must name the same objective as the metric spec), value (number), unit? (e.g. "ms"), source (string/url for provenance), note?, confidence? ("low"|"med"|"high"), researched_at? }; validated server-side (metric/value/source required, confidence ∈ {low,med,high}); surfaces as `benchmark` on the node + /task/detail; absent ⇒ baseline-only judging.', inputSchema: { type: 'object', properties: { task_key: { type: 'string' }, repo_path: { type: 'string' }, test_cmd: { type: 'string' }, metric: { type: 'object' }, benchmark: { type: 'object' } }, required: ['task_key'], additionalProperties: false }, run: async (a, call) => {
    const results = {}; let any = false, failed = false;
    const apply = async (field, fn) => { any = true; const r = await fn(); results[field] = r; if (r && r.error) failed = true; };
    if (a.repo_path !== undefined) await apply('repo_path', () => call('POST', '/git/repo', { key: a.task_key, repo_path: a.repo_path }));
    if (a.test_cmd !== undefined) await apply('test_cmd', () => a.repo_path ? call('POST', '/config', { test_cmds: { [a.repo_path]: a.test_cmd || '' } }) : Promise.resolve({ error: 'test_cmd requires repo_path in the same call (test commands are keyed by absolute repo path)' }));
    if (a.metric !== undefined) await apply('metric', () => call('POST', '/task/metric', { key: a.task_key, spec: a.metric }));
    if (a.benchmark !== undefined) await apply('benchmark', () => call('POST', '/task/benchmark', { key: a.task_key, benchmark: a.benchmark }));
    if (!any) return { error: 'nothing to configure — pass at least one of repo_path, test_cmd, metric, benchmark' };
    return failed ? { ok: false, error: 'one or more fields failed — see results', results } : { ok: true, results };
  } },
{ name: 'measure_task', description: 'Run the task\'s inline metric spec and store the measured value(s) on the node — the MEASURE half of the metric-driven loop. Runs measure_command (+ each guardrail) in the attempt\'s git worktree (branch_task) and parses a number via the spec\'s `parse`. Pass baseline:true to instead measure the repo\'s current main (repo root, no attempt) and store it as the judge\'s reference. Targets the task\'s repo (configure_task repo_path) or repo_path, else the workspace. Requires a metric spec (configure_task metric) and a git repo (branch_task auto-inits one). Result surfaces as `measurement` on the node + /task/detail.', inputSchema: { type: 'object', properties: { task_key: { type: 'string' }, baseline: { type: 'boolean' }, repo_path: { type: 'string' } }, required: ['task_key'], additionalProperties: false }, run: (a, call) => call('POST', '/task/measure', { key: a.task_key, baseline: a.baseline, repo_path: a.repo_path }) },
{ name: 'branch_task', description: 'Backcompat/internal escape hatch for creating an isolated git worktree + branch (orch/attempt/<key>) for a task attempt. Routine agents should use subconscious_assignment action:"prepare", which also handles anchor selection, wiring, judge pairing, repo/test config, and worktree allocation. Targets the task\'s repo (configure_task repo_path) or repo_path, else the workspace. Workspace fallback is rejected when that graph repo belongs to a named multi-repo workspace; pass repo_path or configure the task first. If the target repo is not a git repo yet, it is initialized automatically first.', inputSchema: { type: 'object', properties: { task_key: { type: 'string' }, repo_path: { type: 'string' }, base: { type: 'string', description: 'Git ref to branch from (default: HEAD)' } }, required: ['task_key'], additionalProperties: false }, run: async (a, call) => {
    // Auto-init: if the target isn't a git repo yet, hit the same /git/init endpoint the old
    // standalone git_init tool used, so the prerequisite is implicit.
    const st = await call('GET', `/git/status?${q({ key: a.task_key, repo_path: a.repo_path })}`);
    if (st && !st.error && !st.isRepo) {
      const init = await call('POST', '/git/init', { key: a.task_key, repo_path: a.repo_path });
      if (init && init.error) return init;
    }
    return call('POST', '/git/worktree', { key: a.task_key, repo_path: a.repo_path, base: a.base });
  } },
{ name: 'remove_worktree', description: 'Remove a task attempt\'s git worktree and delete its branch (idempotent cleanup). Targets the task\'s repo (configure_task repo_path) or repo_path, else the workspace.', inputSchema: { type: 'object', properties: { task_key: { type: 'string' }, repo_path: { type: 'string' } }, required: ['task_key'], additionalProperties: false }, run: (a, call) => call('POST', '/git/worktree/remove', { key: a.task_key, repo_path: a.repo_path }) },
{ name: 'merge_attempt', description: 'Visible integration action for merging an approved attempt branch (orch/attempt/<key>) back into the base. Judges record APPROVE with subconscious_assignment action:"submit_verdict"; the loop then surfaces action:"merge" and the driver calls this tool. Targets the task\'s repo (configure_task repo_path) or repo_path, else the workspace.', inputSchema: { type: 'object', properties: { task_key: { type: 'string' }, repo_path: { type: 'string' } }, required: ['task_key'], additionalProperties: false }, run: (a, call) => call('POST', '/git/merge', { key: a.task_key, repo_path: a.repo_path }) },
{ name: 'create_feature', description: 'Create the FEATURE-tier integration surface — a long-lived feature branch (orch/feature/<feature_key>) + worktree branched off `base` (default main). This is the tier-1 surface workers integrate into: dispatch attempts with branch_task(base=<orch/feature/...>, repo_path=<feature worktree>) so each attempt forks FROM the feature branch, and merge_attempt(repo_path=<feature worktree>) lands the winner INTO the feature branch (cheap, frequent), NOT into main. Targets the feature key\'s repo (configure_task repo_path) or repo_path, else the workspace; named multi-repo workspaces require an explicit or configured target. Auto-inits the repo if needed. Idempotent. Returns { branch, worktree, head, repo, target }.', inputSchema: { type: 'object', properties: { feature_key: { type: 'string' }, repo_path: { type: 'string' }, base: { type: 'string', description: 'Git ref to branch the feature off (default: main)' } }, required: ['feature_key'], additionalProperties: false }, run: async (a, call) => {
    const st = await call('GET', `/git/status?${q({ key: a.feature_key, repo_path: a.repo_path })}`);
    if (st && !st.error && !st.isRepo) {
      const init = await call('POST', '/git/init', { key: a.feature_key, repo_path: a.repo_path });
      if (init && init.error) return init;
    }
    return call('POST', '/feature/create', { key: a.feature_key, repo_path: a.repo_path, base: a.base });
  } },
{ name: 'merge_feature', description: 'GATED tier-2 step: merge a feature branch (orch/feature/<feature_key>) into main with --no-ff. Returns {merged} or {conflict, files} (auto-aborts to a clean tree on conflict). THIS IS A DISPATCHER DECISION ONLY — the consequential feature->main promotion. Do NOT call it from any auto/heartbeat/loop/judge path; the loop only auto-merges ATTEMPTS into the feature branch (tier-1, merge_attempt), never feature->main. Invoke this exactly once when a human/dispatcher decides the integrated feature is ready to land on main. Targets the feature key\'s repo (configure_task repo_path) or repo_path, else the workspace.', inputSchema: { type: 'object', properties: { feature_key: { type: 'string' }, repo_path: { type: 'string' } }, required: ['feature_key'], additionalProperties: false }, run: (a, call) => call('POST', '/feature/merge', { key: a.feature_key, repo_path: a.repo_path }) },
{ name: 'get_attempt_diff', description: 'Read-only: the diff of an attempt\'s branch (orch/attempt/<key>) against its base, so the judge can review the code an attempt changed. Returns { ok, key, branch, base, stat, diff } where stat is `git diff base...branch --stat` and diff is the full three-dot (merge-base) diff. Targets the task\'s repo (configure_task repo_path) or repo_path, else the workspace.', inputSchema: { type: 'object', properties: { task_key: { type: 'string' }, repo_path: { type: 'string' } }, required: ['task_key'], additionalProperties: false }, run: (a, call) => call('GET', `/attempt/diff?${q({ key: a.task_key, repo_path: a.repo_path })}`) }
  ];
}

module.exports = gitTools;
