'use strict';

function graphTools(deps) {
  const { q, UI_URI, PORT, runSubconsciousAssignment } = deps;
  return [
  { name: 'get_graph', description: 'Get the workspace task graph or a focused slice of it. Default scope "frontier" returns a lean digest that fits large graphs: whole-graph summary counts + the active frontier (ready/in_progress/recently-relevant nodes, their 1-hop neighbors, and weight-guided important deps/context providers) as slim nodes with clipped summaries. scope "all" returns the whole graph (statuses not_ready/ready/in_progress/tested/done/failed/canceled, ghosts, edges) — pair with compact:true for a slimmed projection (per task only id/label/status/deps/assignee), an order of magnitude smaller on a large graph. scope "adjacent" (requires task_key) returns one task plus its immediate neighbourhood: dependencies, cross-workspace ghost dependencies, and dependents. scope "tree" (requires task_key; optional depth) walks VERTICALLY up the task\'s dependency chain (transitive deps) returning each ancestor with summary + depth — ghost deps come back as a frontier (use peek_workspace). For frontier/all: stale done/canceled tasks and superseded notes older than the archive window are swept from the payload (summary.archived counts them) unless include_archived:true — they always stay queryable via search_knowledge/suggest_links.', inputSchema: { type: 'object', properties: { scope: { type: 'string', enum: ['frontier', 'all', 'adjacent', 'tree'], description: 'frontier (default) = lean active-frontier digest; all = whole graph; adjacent = one task + 1-hop neighbourhood (requires task_key); tree = transitive dependency ancestors (requires task_key, optional depth).' }, compact: { type: 'boolean' }, include_archived: { type: 'boolean' }, include_internal: { type: 'boolean', description: 'Include internal diagnostics such as the shared lane projection. Default false.' }, task_key: { type: 'string' }, depth: { type: 'number' } }, additionalProperties: false }, run: (a, call) => {
      const scope = (a && a.scope) || 'frontier';
      if (scope === 'adjacent' || scope === 'tree') {
        if (!a || !a.task_key) return { error: `scope "${scope}" requires task_key` };
        return scope === 'adjacent' ? call('GET', `/task/adjacent?${q({ key: a.task_key })}`) : call('GET', `/task/tree?${q({ key: a.task_key, depth: a.depth })}`);
      }
      return call('GET', `/state?${q({ scope, compact: a && a.compact ? 1 : null, include_archived: a && a.include_archived ? 1 : null, include_internal: a && a.include_internal ? 1 : null })}`);
    } },
{ name: 'internal_lanes', description: 'Read-only diagnostic projection of internal orchestration lanes. Projects current judge/review decision work, learner queues, active work, and user gates into one shared item shape without changing scheduling behavior.', inputSchema: { type: 'object', properties: { compact: { type: 'boolean', description: 'When true, return only lane counts and omit individual items.' } }, additionalProperties: false }, run: async (a, call) => {
      const r = await call('GET', `/state?${q({ scope: 'all', compact: 1, include_internal: 1 })}`);
      if (r && r.internal_lanes) {
        if (a && a.compact) {
          const { items, ...compact } = r.internal_lanes;
          return compact;
        }
        return r.internal_lanes;
      }
      return r && r.error ? r : { error: 'internal lane projection unavailable' };
    } },
{ name: 'get_dependency_summaries', description: 'TIER 1 (cheap, do first): concise summaries of a task\'s dependencies — enough to start without loading full context. Blocking deps are listed first (no weight). Context deps include a relevance weight (0..1, default 0.5) from wired context edges and are sorted highest-first.', inputSchema: { type: 'object', properties: { task_key: { type: 'string' } }, required: ['task_key'], additionalProperties: false }, run: (a, call) => call('GET', `/task/context?${q({ key: a.task_key })}`) },
{ name: 'get_task_detail', description: 'TIER 2 (on demand): full detail for one task — knowledge items, summary, assigned agent, token usage, transcript pointer.', inputSchema: { type: 'object', properties: { task_key: { type: 'string' } }, required: ['task_key'], additionalProperties: false }, run: (a, call) => call('GET', `/task/detail?${q({ key: a.task_key })}`) },
{ name: 'attach_knowledge', description: 'Attach a Tier-2 knowledge item to a task. item = { type: "file"|"snippet"|"link"|"note", value, ... }.', inputSchema: { type: 'object', properties: { task_key: { type: 'string' }, item: { type: 'object' } }, required: ['task_key', 'item'], additionalProperties: false }, run: (a, call) => call('POST', '/overlay/knowledge', { key: a.task_key, item: a.item }) },
{ name: 'record_decision', description: "Capture a durable decision, rationale, or finding from the conversation as a NOTE node in the graph (NOT a todo). It becomes Tier-1 context for related future tasks via context edges + suggest_links. Use when a turn produces lasting knowledge, or when the user says 'remember this'. TEMPORAL: when this decision REPLACES an earlier one, pass `supersedes` (the old note's key) — the old note is stamped invalid (validTo) and kept as history, not deleted, so as-of retrieval can still recover what was true before. `valid_from` (ISO) optionally backdates when this fact became true. CONTRADICTION CHECK: before recording, call search_knowledge for related CURRENT notes. If the new finding clearly contradicts/replaces one, pass `supersedes` with that note's key so the stale note is retired in the same call. If the contradiction is uncertain, do NOT supersede — mention the tension in the summary instead. DUPLICATE GUARD: if the response is { ok:false, duplicate:true, match:{key,title,summary,score} }, a near-identical note already exists — choose: skip (same fact, nothing to add), re-call with supersedes:match.key (this note updates the fact), or re-call with force:true (genuinely distinct, record anyway).", inputSchema: { type: 'object', properties: { title: { type: 'string' }, summary: { type: 'string' }, category: { type: 'string' }, tags: { type: 'array', items: { type: 'string' } }, knowledge: { type: 'array' }, supersedes: { type: 'string' }, valid_from: { type: 'string' }, wires_to: { type: 'array', items: { type: 'string' }, description: 'Task keys this note was discovered during. Creates explicit DAG context edges (always injects, no gate needed). Pass the current task key when creating a note while working a task.' } }, required: ['title', 'summary'], additionalProperties: false }, run: (a, call) => call('POST', '/overlay/note', { title: a.title, summary: a.summary, category: a.category, tags: a.tags, knowledge: a.knowledge, supersedes: a.supersedes, valid_from: a.valid_from, wires_to: a.wires_to, created_by: 'main' }) },
{ name: 'supersede_note', description: 'Mark an existing note (a recorded decision/finding) as superseded by a newer one WITHOUT deleting history: stamps the old note invalid-from the changeover instant and chains old↔new. The newer fact then wins in default search_knowledge, while as-of retrieval can still recover the older fact for a past timestamp. Both notes must already exist (keys like "note:<id>"). Use when a later decision invalidates an earlier recorded one.', inputSchema: { type: 'object', properties: { old_key: { type: 'string' }, new_key: { type: 'string' }, at: { type: 'string' } }, required: ['old_key', 'new_key'], additionalProperties: false }, run: (a, call) => call('POST', '/overlay/note/supersede', { old_key: a.old_key, new_key: a.new_key, at: a.at }) },
{
    name: 'create_gate',
    description: 'Create a gate node — a coordination primitive that blocks a task until an external event satisfies it (daemon restart, commit, human approval). The dispatcher calls this when wiring the DAG; workers do not. The gate is automatically completed by the daemon when the satisfying event occurs (e.g. daemon-restart gates are swept on every boot). kind: "daemon-restart" | "main-commit" | "human-approval".',
    inputSchema: {
      type: 'object',
      properties: {
        kind: { type: 'string', enum: ['daemon-restart', 'main-commit', 'human-approval'] },
        blocking_task_key: { type: 'string', description: 'The task that must wait for this gate to be satisfied.' },
      },
      required: ['kind', 'blocking_task_key'],
      additionalProperties: false,
    },
    run: (a, call) => call('POST', '/overlay/gate', { kind: a.kind, blocking_task_key: a.blocking_task_key, created_by: 'dispatcher' }),
  },
{ name: 'add_dependency', description: 'Add a dependency edge. kind:"blocking" (default) = `to` is blocked by `from` (true prerequisite). kind:"context" = non-blocking link so `from`\'s summary flows into `to` as Tier-1 context EVEN IF `from` is already done (use to wire a new task to relevant existing/completed work). weight (0..1, context edges only) = optional relevance scalar for relevance-ordered traversal; omit ⇒ default. For a CROSS-WORKSPACE ghost edge set from_workspace to the provider\'s absolute path.', inputSchema: { type: 'object', properties: { from: { type: 'string' }, to: { type: 'string' }, from_workspace: { type: 'string' }, kind: { type: 'string', enum: ['blocking', 'context'] }, weight: { type: 'number' } }, required: ['from', 'to'], additionalProperties: false }, run: (a, call) => call('POST', '/overlay/edge', { from: a.from, to: a.to, fromWorkspace: a.from_workspace, kind: a.kind, weight: a.weight }) },
{ name: 'mark_root', description: 'Declare a task a genuine root (no prerequisites, no context providers). Clears the unwired quarantine so it can be claimed. Use ONLY when the task truly relates to nothing existing.', inputSchema: { type: 'object', properties: { task_key: { type: 'string' }, reason: { type: 'string' } }, required: ['task_key'], additionalProperties: false }, run: (a, call) => call('POST', '/mark-root', { task_key: a.task_key, reason: a.reason }) },
{ name: 'remove_dependency', description: 'Remove a dependency edge from -> to (idempotent). Pass kind:"blocking"|"context" to remove only that kind; omit to remove every edge between them. For a CROSS-WORKSPACE ghost edge set from_workspace to the provider\'s absolute path. Use to re-parallelize a graph by dropping a stale prerequisite.', inputSchema: { type: 'object', properties: { from: { type: 'string' }, to: { type: 'string' }, from_workspace: { type: 'string' }, kind: { type: 'string', enum: ['blocking', 'context'] } }, required: ['from', 'to'], additionalProperties: false }, run: (a, call) => call('POST', '/overlay/edge/remove', { from: a.from, to: a.to, fromWorkspace: a.from_workspace, kind: a.kind }) },
{ name: 'suggest_links', description: 'Suggest existing tasks (INCLUDING completed ones) that a task should link to, ranked by label+summary overlap. Call right after creating a task: link DONE matches as kind:"context" so their summaries become context, and true prerequisites as kind:"blocking" — this stops new tasks from piling up as disconnected root nodes.', inputSchema: { type: 'object', properties: { task_key: { type: 'string' } }, required: ['task_key'], additionalProperties: false }, run: (a, call) => call('GET', `/task/suggest?${q({ key: a.task_key })}`) },
{ name: 'search_knowledge', description: 'Lower-level knowledge retrieval primitive for explicit lookup and internal Subconscious use. Foreground agents that need a verdict, prediction, context, anchor, pressure, or approval posture should call ask_subconscious first. For direct retrieval, gated mode with `task_key` returns the same ranked top-k bundle as ungated plus gate metadata: decision:"inject" means the flagged result cleared the context-need gate; decision:"abstain" means nothing cleared auto-inject but ranked results are still visible. Ungated mode returns ranked hits without gate metadata. First gated call may take up to ~90s while the local embedding model lazy-loads. TEMPORAL/AS-OF: by default returns only facts CURRENT now (superseded notes are hidden). Pass `as_of` (ISO timestamp) to get the fact that was current AT THAT TIME, or `history:true` to include superseded notes. TIERED: pass `task_key` to include DAG context_deps first, then RAG fills remaining slots. ITERATIVE: `continue:true` means another reformulated query may surface more relevant notes; pass `exclude_keys` and increment `round` up to 3.', inputSchema: { type: 'object', properties: { query: { type: 'string' }, k: { type: 'number' }, gated: { type: 'boolean' }, as_of: { type: 'string' }, history: { type: 'boolean' }, task_key: { type: 'string' }, exclude_keys: { type: 'array', items: { type: 'string' }, description: 'Note keys already injected in prior rounds — excluded from candidates before ranking.' }, round: { type: 'number', description: 'Retrieval round (1-based, default 1). Rounds >= 3 always return continue:false.' }, complexity: { type: 'number', description: 'Prompt complexity score (0–1) from the model-routing hook. Passed to the gate journal as a task-side feature. Omit if unknown.' } }, required: ['query'], additionalProperties: false }, run: (a, call) => call('GET', `/search?${q({ q: a.query, k: a.k, gated: a.gated ? 1 : undefined, asOf: a.as_of, history: a.history ? 1 : undefined, task_key: a.task_key, exclude_keys: Array.isArray(a.exclude_keys) && a.exclude_keys.length ? a.exclude_keys.join(',') : undefined, round: a.round, complexity: a.complexity })}`) },
{ name: 'entity_context', description: 'Query everything known (conversational facts) AND everything done (tasks) about a named entity. Returns facts (note nodes distilled from conversation or hand-authored) and tasks (execution nodes) wired to this entity in a single unified view — the entity is the join key across both graphs. Use to answer "what do we know about X and what have we done with X?" without separate searches. Pass as_of (ISO timestamp) to see only facts that were current at that time.', inputSchema: { type: 'object', properties: { entity_name: { type: 'string', description: 'The entity name to look up (case-insensitive exact match against registered entity nodes).' }, workspace: { type: 'string', description: 'Workspace path. Defaults to the session workspace when omitted.' }, as_of: { type: 'string', description: 'Optional ISO timestamp — filter facts to only those valid at this point in time.' } }, required: ['entity_name'], additionalProperties: false }, run: async (a, call) => {
    const lookupResp = await call('GET', `/entity?${q({ name: a.entity_name, workspace: a.workspace })}`);
    if (!lookupResp || lookupResp.error) {
      return { ok: false, error: lookupResp ? lookupResp.error : 'entity lookup failed', entity_name: a.entity_name };
    }
    const entityId = lookupResp.id;
    return call('GET', `/entity/${encodeURIComponent(entityId)}/context?${q({ workspace: a.workspace, asOf: a.as_of })}`);
  } },
{ name: 'graph_delta', description: "What changed in the graph since an ISO-8601 timestamp — the read-only change sensor for nightly-QA / catch-up sweeps. Returns { since, now, counts, status_changes (tasks whose status changed after T, incl. reached done/tested/canceled), tasks_created, notes_added (decisions/findings recorded after T), merges (judge/merge verdicts that carry a timestamp; timestamp-less verdicts are omitted) }. Derived purely from existing timestamps — never mutates the graph.", inputSchema: { type: 'object', properties: { since: { type: 'string', description: 'ISO-8601 timestamp, e.g. 2026-06-09T00:00:00Z' } }, required: ['since'], additionalProperties: false }, run: (a, call) => call('GET', `/graph/delta?${q({ since: a.since })}`) },
{ name: 'resolve_context_handle', description: 'Resolve a reversible context compression (CCR) handle emitted by /search?reversible_context=1 back to the original graph task, note, or knowledge source chunk content. Read-only.', inputSchema: { type: 'object', properties: { workspace: { type: 'string' }, handle: { type: ['object', 'string'] } }, required: ['handle'], additionalProperties: false }, run: (a, call) => call('POST', '/context/resolve', { workspace: a.workspace, handle: a.handle }) },
{ name: 'peek_workspace', description: 'Load another workspace\'s full task graph on demand (does not change current). Inspect a ghost dependency\'s source.', inputSchema: { type: 'object', properties: { workspace: { type: 'string' } }, required: ['workspace'], additionalProperties: false }, run: (a, call) => call('GET', `/peek?${q({ workspace: a.workspace })}`) }
  ];
}

module.exports = graphTools;
