'use strict';

function guidanceTools(deps) {
  const { q, UI_URI, PORT, runSubconsciousAssignment } = deps;
  return [
  { name: 'request_guidance', description: 'LAST RESORT escalation — predict-by-default from KB first, only call this on a gate miss. The seam ENFORCES it: every call is run through the ask-vs-predict gate over recalled user-preference notes BEFORE reaching the user, so a confident project-local preference match auto-resolves the question (returns predicted:true + the answer) without ever pausing the loop or queuing for you. Only when no confident preference matches (gate says "ask") does this queue a decision nudge for a relevant live agent session (ambiguous intent, irreversible/outward action, low-confidence high-impact, repeated failure, scope expansion). Unresolved guidance never holds task readiness or scheduling. Irreversible/outward/high-impact/scope-expansion/repeated-failure decisions ALWAYS escalate (the gate hard-overrides prediction) — pass the matching flag or rely on keyword detection. severity "blocking" is retained for compatibility; "review" is reserved for internal low-stakes housekeeping.', inputSchema: { type: 'object', properties: { question: { type: 'string' }, context: { type: 'string' }, trigger: { type: 'string' }, severity: { type: 'string', enum: ['blocking', 'review'] }, session_id: { type: 'string', description: 'Caller session/conversation id — injected by the seam to bind this escalation to the claiming task (origin_task) for the staleness sweep.' }, irreversible: { type: 'boolean' }, outward: { type: 'boolean' }, highImpact: { type: 'boolean' }, scopeExpansion: { type: 'boolean' }, repeatedFailure: { type: 'boolean' } }, required: ['question'], additionalProperties: false }, run: (a, call) => call('POST', '/guidance', { question: a.question, context: a.context, trigger: a.trigger, severity: a.severity, session_id: a.session_id, irreversible: a.irreversible, outward: a.outward, highImpact: a.highImpact, scopeExpansion: a.scopeExpansion, repeatedFailure: a.repeatedFailure }) },
{ name: 'list_guidance', description: 'List unresolved user-attention guidance for the live agent to surface. Mechanical review items are returned separately as internal diagnostics and should be handled by judge/headless drains, not by asking the user.', inputSchema: { type: 'object', properties: {}, additionalProperties: false }, run: (a, call) => call('GET', '/guidance') },
{ name: 'ask_gate', description: 'Decide ASK-the-user vs PREDICT-from-KB for a pending decision. The daemon recalls stored user-preference notes (semantic match, grounded on category:"preference" + general decision notes) and runs the ask-by-default heuristic gate (lib/ask-gate.js): a high-confidence, specific, project-local preference match returns decision:"predict" WITH the matched note; otherwise decision:"ask" (escalate via request_guidance). Decisions that are irreversible/outward-facing/high-impact/scope-expansion/repeated-failure ALWAYS return "ask" — pass the matching flag, or rely on conservative keyword detection on the decision text. Every verdict is journaled to .graph/ask-journal.jsonl.', inputSchema: { type: 'object', properties: { decision: { type: 'string', description: 'The pending decision/question you would otherwise ask the user.' }, irreversible: { type: 'boolean' }, outward: { type: 'boolean' }, highImpact: { type: 'boolean' }, scopeExpansion: { type: 'boolean' }, repeatedFailure: { type: 'boolean' } }, required: ['decision'], additionalProperties: false }, run: (a, call) => call('POST', '/ask-gate', { decision: a.decision, irreversible: a.irreversible, outward: a.outward, highImpact: a.highImpact, scopeExpansion: a.scopeExpansion, repeatedFailure: a.repeatedFailure }) },
{ name: 'block_task', description: 'Explicitly block a task from being auto-dispatched by the heartbeat loop. A blocked task stays out of the spawn queue regardless of its dep status — the block is sticky and survives graph rebuilds. Use to gate expensive or risky tasks that should not run without explicit approval. Call unblock_task to release. The block is visible on get_task_detail and in the graph.', inputSchema: { type: 'object', properties: { task_key: { type: 'string' }, reason: { type: 'string', description: 'Why this task is blocked (stored for observability).' } }, required: ['task_key'], additionalProperties: false }, run: (a, call) => call('POST', '/overlay/block', { key: a.task_key, reason: a.reason }) },
{ name: 'unblock_task', description: 'Clear an explicit block set by block_task, making the task eligible for auto-dispatch again (if its deps are satisfied). Idempotent — no-op if the task was not blocked.', inputSchema: { type: 'object', properties: { task_key: { type: 'string' } }, required: ['task_key'], additionalProperties: false }, run: (a, call) => call('POST', '/overlay/unblock', { key: a.task_key }) },
// All agent-driven supersede ops should go through this tool — direct POST /supersede in scripts
  // is only for non-agent bootstrap paths (e.g. inject scripts that predate MCP).
  { name: 'supersede_task', description: 'Retire an old task in favor of a replacement, linking them, so a replan reconciles cleanly instead of leaving orphaned duplicates.', inputSchema: { type: 'object', properties: { old_task_key: { type: 'string' }, new_task_key: { type: 'string' }, reason: { type: 'string' } }, required: ['old_task_key', 'new_task_key'], additionalProperties: false }, run: (a, call) => call('POST', '/supersede', { old_key: a.old_task_key, new_key: a.new_task_key, reason: a.reason }) }
  ];
}

module.exports = guidanceTools;
