'use strict';

function knowledgeTools(deps) {
  const { q, UI_URI, PORT, runSubconsciousAssignment } = deps;
  return [
  { name: 'enqueue_kb', description: 'Mine a repo and enqueue ALL candidates into the learner queue (no cap, no LLM). Fast first step before drain_kb_batch. Pass outDir to override the default .zonoid/onboard/<repo-name> location.', inputSchema: { type: 'object', properties: { repo: { type: 'string' }, outDir: { type: 'string' } }, required: ['repo'], additionalProperties: false }, run: (a, call) => call('POST', '/onboard/enqueue', { repo: a.repo, outDir: a.outDir }) },
{ name: 'drain_kb_batch', description: 'Process one batch of queued KB candidates via LLM. Call repeatedly until status.done is true, then review the generated onboard-notes.json and call inject_kb to push approved notes into the graph. Returns { ok, status: { total, processed, remaining, done, kept } }.', inputSchema: { type: 'object', properties: { repo: { type: 'string' }, outDir: { type: 'string' }, batchSize: { type: 'number' } }, required: ['repo', 'outDir'], additionalProperties: false }, run: (a, call) => call('POST', '/onboard/drain-next', { repo: a.repo, outDir: a.outDir, batchSize: a.batchSize }) },
{ name: 'drain_kb_queue', description: 'Fire-and-forget background drain: kicks off the full queue drain in the daemon background. Default auto-injects validated notes on completion; pass autoInject:false only when a manual review gate is required. Poll with drain_kb_queue_status to check progress.', inputSchema: { type: 'object', properties: { repo: { type: 'string' }, outDir: { type: 'string' }, batchSize: { type: 'number' }, autoInject: { type: 'boolean', description: 'Set false to require explicit inject_kb after drain completion. Defaults to true.' } }, required: ['repo', 'outDir'], additionalProperties: false }, run: (a, call) => call('POST', '/onboard/drain-queue', { repo: a.repo, outDir: a.outDir, batchSize: a.batchSize, autoInject: a.autoInject }) },
{ name: 'drain_kb_queue_status', description: 'Get the current status of a background drain job started by drain_kb_queue. Returns { ok, status: { repo, outDir, total, processed, remaining, done, error, needsReview, injected } }.', inputSchema: { type: 'object', properties: { repo: { type: 'string' }, outDir: { type: 'string' } }, required: ['repo', 'outDir'], additionalProperties: false }, run: (a, call) => call('GET', `/onboard/drain-queue?${new URLSearchParams({ repo: a.repo, outDir: a.outDir })}`) },
{ name: 'inject_kb', description: 'Explicitly inject reviewed onboarding KB notes into the graph for a repo/outDir. This is the human-gated counterpart to scripts/onboard-learn.js --inject --confirm.', inputSchema: { type: 'object', properties: { repo: { type: 'string' }, outDir: { type: 'string' } }, required: ['repo', 'outDir'], additionalProperties: false }, run: (a, call) => call('POST', '/onboard/inject', { repo: a.repo, outDir: a.outDir }) },
{ name: 'get_learnings', description: "Aggregate the graph's accumulated learning (attempt verdicts, recent failures, recent completions) — the digest a planner reads to decide what to try next. Pass compact:true for a lean payload (trimmed verdicts + rejected ledger only, recent/failures dropped) to cut re-attended context cost.", inputSchema: { type: 'object', properties: { compact: { type: 'boolean' } }, additionalProperties: false }, run: (a, call) => call('GET', a.compact ? '/learnings?compact=1' : '/learnings') }
  ];
}

module.exports = knowledgeTools;
