'use strict';

function loopTools(deps) {
  const { q, UI_URI, PORT, runSubconsciousAssignment } = deps;
  return [
  { name: 'next_action', description: 'HEARTBEAT (drives the WHOLE loop registry in ONE call): returns { loops: [ { loopId, action: spawn|review|merge|resolve_merge_conflict|idle|plan|stop|await_user, tasks?, task?, next_poll_seconds?, budget_remaining, review_items? } ] } — one entry per ACTIVE loop. Fan out task spawns per loopId; same-node review and integration are visible loop actions after tests; edge-judge drains remain daemon-owned internal work. Reschedule ONE wakeup at the MIN next_poll_seconds across active loops; the whole heartbeat is done only when every entry reports stop. action:plan means that loop drained but self-planning is on.', inputSchema: { type: 'object', properties: {}, additionalProperties: false }, run: (a, call) => call('GET', '/next-action') },
{ name: 'loop_control', description: 'Manage heartbeat loops — ONE tool, action: "start" | "stop" | "status". action:"start": start a loop and INSERT it into the registry (never clobbers an existing loop) — pass explicit token controls (tokenBudget, maxIterations, minPoll, maxPoll, estPerTick, batch) and an optional `session` (the driving conversation, so a cooperative-stop on its claimed task halts THIS loop within one tick); optional `loopId` restarts that specific loop in place, otherwise the daemon mints a UUID; returns { ok, loopId, loop }; hard caps. action:"stop": stop a specific loop — `loopId` REQUIRED; returns { ok, loopId }. action:"status": read loop state — with `loopId`, that loop\'s entry { active, iterations, spent, budget, config, ... }; omit loopId for the whole registry { loops: { [loopId]: entry } }. Token-control params and `session` apply ONLY to action:"start".', inputSchema: { type: 'object', properties: { action: { type: 'string', enum: ['start', 'stop', 'status'], description: '"start" = insert a new loop (or restart in place with loopId); "stop" = stop one loop (loopId required); "status" = one loop or, without loopId, the whole registry.' }, loopId: { type: 'string', description: 'start: optional, restarts this loop in place; stop: REQUIRED; status: optional, omit for all loops.' }, tokenBudget: { type: 'number' }, maxIterations: { type: 'number' }, minPoll: { type: 'number' }, maxPoll: { type: 'number' }, estPerTick: { type: 'number' }, batch: { type: 'number' }, session: { type: 'string' } }, required: ['action'], additionalProperties: false }, run: (a, call) => { const { action, ...rest } = a; if (action === 'stop') return rest.loopId ? call('POST', '/loop/stop', { loopId: rest.loopId }) : { error: 'loopId is required for action:"stop"' }; if (action === 'status') return call('GET', rest.loopId ? `/loop/status?loopId=${encodeURIComponent(rest.loopId)}` : '/loop/status'); return call('POST', '/loop/start', rest); } }
  ];
}

module.exports = loopTools;
